language: c

branches:
  only:
    - master
    - /^areastat-.*/
matrix:
  fast_finish: true
  include:
  - os: linux
    env:
    - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=OFF ARCH="x86_64"
  - os: linux
    env:
    - MATRIX_EVAL="CC='gcc -m32'" CF="-DBUILD_SHARED_LIBS=OFF -DCMAKE_LIBRARY_PATH=/usr/lib32"
      PACKAGES="gcc-multilib lib32z1-dev" ARCH="i686"
  - os: osx
    env:
    - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=OFF ARCH="x86_64"
  - os: osx
    env:
    - MATRIX_EVAL="CC='gcc -m32'" CF=-DBUILD_SHARED_LIBS=OFF ARCH="i686"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - git clone https://github.com/huskyproject/huskylib ~/build/huskyproject/huskylib
  - git clone https://github.com/huskyproject/smapi ~/build/huskyproject/smapi
  - git clone https://github.com/huskyproject/fidoconf ~/build/huskyproject/fidoconf
  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
    --no-upgrade -qq $PACKAGES; fi
script:
  - eval "${MATRIX_EVAL}"
  - cd  ~/build/huskyproject/huskylib
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/smapi
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/fidoconf
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake .. ${CF} -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci
  - cmake --build .
  - cpack
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpack -G RPM; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpack -G DEB; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then for file in *.rpm; do mv $file
    $(basename $file .rpm).${ARCH}.rpm; done; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then for file in *.deb; do mv $file
    $(basename $file .deb).${ARCH}.deb; done; fi
  - for file in *.tar.gz; do mv $file $(basename $file .tar.gz).${ARCH}.tar.gz;
    done
deploy:
  provider: releases
  api_key:
    secure: IMmPl5t637c3Hdi3j4nIOi2ZBQNHbBuhIe+ksIknkDZZnUQFEXncE80lLw72SlaBHPSuw1N4EvVJKAHjbMdfCrp7gpEkcFfvnk/fe2fNKK3kRO+FphtvRJMyq2c3pd2x0WHVW1D0NSCjoE0WQf/nwFUYp3+HCQ1lKT74UNfLpvuflGUb7Lgbp01vtRH5ToejFmN3kpr9bX7syex0WJDNqe0eH9fEV7scjzM6nalTzIZTOpZCoHEivKn7IG2j3nB8kxg2xxvnMpE0oKSRj5bq6V8k34m4ds2uYRt1Hz+zo/N6pfw2cjwVP9Ho6iPdkGueWeMxBkQH0/w70Db2x6pXvQpX5kQOX+vTrPWIkytLKgYFXUvor7yGrWhF/tsVHiMOj8KbpX+lemfITXhP/4ug1VoeZIo/NoVOJ9bA+s0JtSnEOzIt/fVIKklA7yGm0OLL9HZJvpBqPnDRYiusoAngA4YFcg6I0+OBlY9hZJSKDhevlZrvhsMgIqqz0xKEMy/7NLL5TZeo0rEo1sZhPPKltpKxOZx3X6uzl/Bxwype6AOSVNLKD94OYlb8fpmMlgmCC1OP+DC9XkN4BNJs8H6OLESz8m935APhdX1qhsglHKquhizxLhwAjKdJKUydK9/Q2S9B0/GuSUqDP+aMdGHdrFAKo5ZseeYPdQ/bfFv0tpM=
  file_glob: true
  skip_cleanup: true
  file: 
    - $TRAVIS_BUILD_DIR/build/*.rpm
    - $TRAVIS_BUILD_DIR/build/*.deb
    - $TRAVIS_BUILD_DIR/build/*.tar.gz
  on:
    tags: true
    branch: master
